[package]
name = "slice-language-server"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.29"
slicec = "0.2.1"
tokio = { version = "1.33.0", features = ["full"] }
tower-lsp = "0.20.0"

[profile.release]
opt-level = "z"
strip = "symbols"
